### PR TITLE
Manually trigger onComplete Event if href and location.href are identical

### LINKED ISSUE #4: Router events shouldn't be triggered when router.push to the same route

### PR DESCRIPTION
**Pull request by ablond**

### CODE REVIEW

**Review by joulev — CHANGES_REQUESTED** [review]
Actually this doesn't work because while `href` can be something like `/`, `window.location.href` will also include the hostname and other information (e.g. `http://localhost:3000`), so the equality is never reached.

Can we make it such that we only trigger `onStart` when the href is different from the current page href (instead of all the time)? Something like this, so consistent with the `<Link>` behaviour.

https://github.com/joulev/nextjs13-appdir-router-events/blob/e4d69e99e17ead03b37c0094717de40e74f963fb/lib/router-events/patch-router/link.tsx#L32-L33

**Comment by ablond** [comment]
Thank you for your reply, my implementation was indeed too light :)

I think we have 2 subjects here : 
- First :  `href` can be something like `/my-path` or like `my.domain/my-path` 
Something like this would work (in both router.tsx and link.tsx when it comes to detecting a url changes)

```javascript
const { pathname, search, hash } = window.location;
const [href] = args;

if (isValidUrl(href) && href !== window.location.href) onStart();
if (!isValidUrl(href) && href !== pathname + search + hash) onStart();

const isValidUrl = urlString => {
  try {
    return Boolean(new URL(urlString));
  }
  catch(e){
    return false;
  }
}
```

- Second : Should we trigger `onStart` and `onComplete` even if the route is identical, or not trigger any events ?
My point is : if a user clicks on a link that redirects to the same page and nothing happens, will this be seen as a bug ? If we have a (very fast) loader / spinner / progressbar, is that a better ux ? It's an open question :)

What do you think about that ?

**Comment by ablond** [comment]
Now that i think of it, there is also the trailingSlash option to manage : https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash

**Comment by joulev** [comment]
> Now that i think of it, there is also the trailingSlash option to manage : https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash

And we need to handle basePath as well, and after checking a bit, I found [`addBasePath`](https://github.com/vercel/next.js/blob/400ccf7b1c802c94127d8d8e0d5e9bdf9aab270c/packages/next/src/client/add-base-path.ts) which can do both for us.

> First :  href can be something like /my-path or like my.domain/my-path
Something like this would work (in both router.tsx and link.tsx when it comes to detecting a url changes)

I decided to move the logic to check this to a separate file instead, then use that in both the `Link` component and the `useRouter` hook.

> Second : Should we trigger onStart and onComplete even if the route is identical, or not trigger any events ? My point is : if a user clicks on a link that redirects to the same page and nothing happens, will this be seen as a bug ? If we have a (very fast) loader / spinner / progressbar, is that a better ux ? It's an open question :)

I personally think not triggering any events is better. That being said, this is not a NPM package but a copy-and-paste solution that anyone can customise to their need, the code is fairly simple as well, if anyone wants a different behaviour then it can be easily done in a few lines of code, so I don't think it is an important issue.

So considering the `Link` component needs to be updated as well, I instead decided to make 9875d235afced30732a1c238cae5c18d5d814472 to fix everything, hence will close this PR in favour of that commit. Thank you for your contributions and suggestions!

**Pull request closed without merging**
